config/routes.rb
Rails.application.routes.draw do

  get 'help' => 'help#index', as: :help_index
  get 'help/:action' => 'help#:action', as: :help

  get 'welcome/index'
  get 'init' => 'welcome#init'

  get 'wallpaper/:id' => 'wallpapers#show', as: :wallpaper

  get 'search' => 'wallpapers#search', as: :search
  get 'search/tags.json' => 'tags#search', as: :tags_search
  get 'search/untagged' => 'wallpapers#untagged', as: :search_untagged

  post 'wallpaper/edit' => 'wallpapers#edit', as: :wallpaper_edit

  resources :tags

  namespace :admin do
    get 'wallpapers/import', as: :import_wallpaper
    post 'wallpapers/do_import', as: :do_import_wallpaper
  end

  root 'wallpapers#index'
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true

  before_validation :parse_name

  has_and_belongs_to_many :wallpapers, -> { order('rand()') }

  has_many :aliases, class_name: 'Tag', foreign_key: 'alias_of_id'
  has_one :alias_of, class_name: 'Tag', foreign_key: 'id', primary_key: 'alias_of_id'
  has_one :background_wallpaper, class_name: 'Wallpaper', foreign_key: 'id', primary_key: 'wallpaper_id'


  has_many :implications, class_name: 'TagImplication'
  has_many :implied_tags, :through => :implications

  has_many :implied_by, class_name: 'TagImplication', foreign_key: 'implied_tag_id'

  enum category: [:general, :copyright, :character, :artist, :circle]

  # Parse the name of the tag to extract cateogry if present
  def parse_name
    self.name.downcase.chomp! ':'

    if self.name.include? ':'
      parts = self.name.split(':')

      if %w(copyright character artist circle).include? parts[0]
        self.category = parts[0].to_sym
      end

      self.name = parts[1]
    end
  end

  def update_wallpapers_count
    nb_wallpapers = Tag.joins(:wallpapers).where(:id =>  self.id).count
    self.wallpapers_count = nb_wallpapers || 0
    self.save
  end

  def update_implied_tags(new_tags_names, tags_names_to_remove)
    # Adding new tag
    if new_tags_names.present?
      new_tags_list = Tag.where :name => new_tags_names.map{|name| name.downcase}

      new_tags_list.each do |tag|
        self.implied_tags << tag unless self.implied_tags.include? tag and (tag.imply? self or tag.implication_of? self)
      end
    end

    # Removing tags
    if tags_names_to_remove.present?
      tags_to_remove = Tag.where :name => tags_names_to_remove.map{|name| name.downcase}

      tags_to_remove.each do |tag|
        self.implied_tags.delete tag
      end
    end
  end

  def imply?(tag)
    self.implied_tags.each do |i_tag|
      return true if i_tag.id == tag.id or i_tag.imply? tag
    end

    false
  end

  def implication_of?(tag)
    self.implied_by.each do |tag_impl|
      return true if tag_impl.tag.id == tag.id or tag_impl.tag.implication_of? tag
    end

    false
  end

  def self.list_ids_by_names(names)
    Tag.where(LIST_IDS_BY_NAME_QUERY, names, names, names).ids
  end

  def self.contains_word(word)
    where('name LIKE :word', :word => "%#{word}%").order(:name)
  end


  def self.list_with_implied(names)
    return [] if names.blank?

    tags = where :name => names
    res = []

    tags.each do |tag|
      res << tag
      res.concat list_implied_tags(tag)
    end

    res
  end

  private
    LIST_IDS_BY_NAME_QUERY = 'name IN (?) OR EXISTS (SELECT 1 FROM tags alias WHERE tags.alias_of_id = alias.id AND alias.name IN (?)) OR EXISTS (SELECT 1 FROM tags alias WHERE alias.alias_of_id = tags.id AND alias.name IN (?))'

    def self.list_implied_tags(tag)

    return [] if tag.blank? or (not tag.instance_of?(Tag)) or tag.implied_tags.blank?

    res = []

    tag.implied_tags.each do |tag|
      res << tag
      res.concat list_implied_tags(tag)
    end

    res
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order(:name)
  end

  def show
    @tag = Tag.find_by! :id => params[:id]

    if @tag.alias_of_id != nil
      @tag = @tag.alias_of
    end

    @wallpapers = @tag.wallpapers.take 20

    @background_wallpaper = @tag.background_wallpaper
  end

  def search
    term = params[:term]
    @tags = Tag.where('name LIKE ?', "#{term}%").order(:name).pluck(:name)
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to tags_path
    else
      render 'new'
    end
  end

  def edit
    @tag = Tag.includes(:implied_tags).find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)

      # Handle implied_tags
      edit_query = QueryParser.new.parse_query(params[:implications])
      @tag.update_implied_tags edit_query[:tags][:related], edit_query[:tags][:exclude]
      @tag.save!

      redirect_to tags_path
    else
      render 'edit'
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end

  private

    def tag_params
      params.require(:tag).permit(:name, :type, :wallpaper_id, :bg_x, :bg_y, :category)
    end
end

app/helpers/tags_helper.rb
module TagsHelper

  def background_string(wallpaper, x_pos, y_pos)
    if wallpaper.nil?
      'background: #6a819a'
    else
      raw("background: url('#{image_url wallpaper.wall_path}') no-repeat #{x_pos} #{y_pos}")
    end
  end

end

app/views/tags/_edit_header_form.html.erb
<%= form_for @tag do |f| %>

    <p><%= f.label :wallpaper_id %><br>
      <%= f.text_field :wallpaper_id %></p>

    <p>
        <%= f.label :bg_x %><br>
        <%= f.text_field :bg_x %>
        <span class="help">value in px or % or kw in [left, center, right]</span>
    </p>

    <p>
      <%= f.label :bg_y %><br>
      <%= f.text_field :bg_y %><br>
      <span class="help">value in px or % or kw in [top, middle, bottom]</span>
    </p>

    <p><button type="button" id="tag_header_preview">Preview</button></p>
    <p><%= f.submit %></p>


    <script type="text/javascript">
    var wallpaperUrlTemplate = '<%= url_for wallpaper_path(':id', format: 'json') %>';
    </script>
<% end #form %>

app/views/tags/_form.erb
<%= form_for @tag do |f| %>

    <% if @tag.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@tag.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @tag.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p><%= f.label :name %><br>
      <%= f.text_field :name %></p>

    <p><%= f.label :type %></p>
    <p><%= f.radio_button :type, :general %> General</p>
    <p><%= f.radio_button :type, :title %> Title</p>
    <p><%= f.radio_button :type, :character %> Character</p>

    <p><%= f.submit %></p>
<% end #form %>

app/views/tags/_form.html.erb
<%= form_for @tag, :html => { :class => 'pure-form' } do |f| %>

    <% if @tag.errors.any? %>
        <div id="error_explanation">
          <h2>
            <%= pluralize(@tag.errors.count, "error") %> prohibited
            this article from being saved:
          </h2>
          <ul>
            <% @tag.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <fieldset>

      <div class="pure-control-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="pure-control-group">
        <%= f.label :category %>
        <ul class="unstyled list-inline">
          <li><label class="pure-radio tag-category-general">
            <%= f.radio_button :category, :general %> &nbsp;&nbsp; General
          </label></li>
          <li><label class="pure-radio tag-category-copyright">
            <%= f.radio_button :category, :copyright %> &nbsp;&nbsp; Copyright
          </label></li>
          <li><label class="pure-radio tag-category-character">
            <%= f.radio_button :category, :character %> &nbsp;&nbsp; Character
          </label></li>
          <li><label class="pure-radio tag-category-artist">
            <%= f.radio_button :category, :artist %> &nbsp;&nbsp; Artist
          </label></li>
          <li><label class="pure-radio tag-category-circle">
            <%= f.radio_button :category, :circle %> &nbsp;&nbsp; Circle
          </label></li>
        </ul>
      </div>

    <div class="pure-control-group">
        <%= label_tag :implications %>
        <div class="inbl">
            <%= text_field_tag :implications, params[:implications], class: 'tag-autocomplete-field w100'  %></p>
    <ul id="implied_tag_list">
<% @tag.implied_tags.each do |tag| %>
        <li><span class="tag-category-<%= tag.category %>"><%= tag.name %></span>
        &nbsp;(<a href="#">remove</a>)</li>
<% end %>
    </ul>

        </div>
    </div>

    </fieldset>

    <p class="txtright"><%= f.submit class: 'btn btn-flat' %></p>
<% end #form %>

app/views/tags/edit.html.erb
<h1>Edit tag</h1>

<div class="card w800p center">
  <%= render 'form' %>
</div>

<%= link_to raw('<i class="fa fa-arrow-left"></i> Back'), tags_path, class: 'btn' %>

app/views/tags/index.html.erb
<h1>Tags#index</h1>

<p class="mbs"><%= link_to 'New tag', new_tag_path, class: 'btn' %></p>


<table class="table hover">
  <col />
  <col width="120">
  <col width="80" span="3">
  <thead>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th colspan="3">&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td class="tag-category-<%= tag.category %>"><%= tag.category %></td>
        <td class="action-cell"><%= link_to 'Show', tag_path(tag) %></td>
        <td class="action-cell warning"><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td class="action-cell danger"><%= link_to 'Destroy', tag_path(tag),
                                                   method: :delete,
                                                   data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/tags/new.html.erb
<h1>New tag</h1>

<div class="card pure-form">
<%= render 'form' %>
</div>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<section class="tag-brand" style="<%= background_string @background_wallpaper, @tag.bg_x, @tag.bg_y %>">
  <div>
    <header>
      <h1><%= @tag.name %></h1>

      <div>
        <strong>Alias&nbsp;:</strong><br>
        <%= @tag.aliases.map{|v| v.name}.join(', ') %>
      </div>
    </header>


    <ul class="tag-attrs">
      <li>Category : <%= @tag.category %></li>
      <li>Nb wallpapers : <%= @tag.wallpapers_count %></li>
    </ul>
  </div>

  <% if not @background_wallpaper.nil? %>
  <a href="<%= url_for wallpaper_path(@background_wallpaper) %>" class="wall-bg-link">
    <i class="fa fa-image fa-fw"></i>
  </a>
  <% end %>
  <a href="#set-header-bg-modal" data-toggle="modal" class="edit-btn">
    <i class="fa fa-pencil fa-fw"></i>
  </a>

</section>


<%= render :partial => 'shared/wallpaper_list', :locals => { :infinite => false, :wallpapers => @wallpapers } %>

<% if @tag.wallpapers_count > @wallpapers.size %>

<div style="text-align: center">

  <a href="<%= url_for search_path(:q => @tag.name) %>" class="btn">Plus de fonds de wallpapers</a>

</div>
<% end %>

<div id="set-header-bg-modal" title="Edit header background" data-width="500px" style="display: none">

  <div class="tabs">
      <nav>
        <ul>
          <li><a href="#te-gene-data" data-toggle="tab" class="active">General data</a></li>
          <li><a href="#te-head-bg" data-toggle="tab">Header background</a></li>
          <li><a href="#te-delete" data-toggle="tab">Delete tag</a></li>
        </ul>
      </nav>

      <div class="tabs-pane">
        <section class="pane active" id="te-gene-data">
          <%= render 'form' %>
        </section>

        <section class="pane" id="te-head-bg">
          <%= render 'edit_header_form' %>
        </section>

        <section class="pane" id="te-delete">

          <p class="txtcenter">
            <%= link_to 'Destroy', tag_path(@tag), method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>

        </section>
      </div>
  </div>



</div>