config/routes.rb
Rails.application.routes.draw do

  get 'help' => 'help#index', as: :help_index
  get 'help/:action' => 'help#:action', as: :help

  get 'welcome/index'
  get 'init' => 'welcome#init'

  get 'wallpaper/:id' => 'wallpapers#show', as: :wallpaper

  get 'search' => 'wallpapers#search', as: :search
  get 'search/tags.json' => 'tags#search', as: :tags_search
  get 'search/untagged' => 'wallpapers#untagged', as: :search_untagged

  post 'wallpaper/edit' => 'wallpapers#edit', as: :wallpaper_edit

  resources :tags

  namespace :admin do
    get 'wallpapers/import', as: :import_wallpaper
    post 'wallpapers/do_import', as: :do_import_wallpaper
  end

  root 'wallpapers#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : 'imeji' %></title>

    <%= stylesheet_link_tag    'knacss', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header id="header" role="banner">
      <nav>
        <ul>
          <li><a href="<%= url_for :root %>" class=""><i class="fa fa-home fa-fw"></i></a></li>
          <li><%= form_tag :search, :method => 'get', :id => 'app_search', :enforce_utf8 => false do %>
            <label for="search"><i class="fa fa-search fa-fw"></i></label><!--
            --><%= text_field_tag :q, @queryString, :id => 'search', :placeholder => 'Rechercher', :autocomplete => 'off' %>
            <button type="submit" style="display: none"><i class="fa fa-search fa-fw"></i></button>
            <% end %></li>
          <li><%= link_to raw('<i class="fa fa-tags fa-fw"></i>'), tags_path %></li>
          <li><a href="#head-admin" data-toggle="header-submenu"><i class="fa fa-wrench fa-fw"></i></a></li>
          <li><a href="<%= url_for :help_index %>"><i class="fa fa-question fa-fw"></i></a></li>
        </ul>
      </nav>
      <div id="head-admin" class="header-sub">
        <div class="header-subtitle">Tools</div>
        <nav>
        <ul>
          <li><a href="<%= url_for :admin_import_wallpaper %>" title="Import"><i class="fa fa-upload fa-fw"></i></a></li>
          <li><a href="<%= url_for :search_untagged %>" title="Untagged"><i class="fa fa-ban fa-fw"></i></a></li>
          <li class="spacer"></li>
        </ul>
        </nav>
      </div>
    </header>

    <div id="main" role="main">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>